spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shenchuang006/spring-cloud
          search-paths: config-files
          username: 745372213@qq.com
          password: 19890302dear
server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/