server:
  port: 8769
spring:
  application:
    name: config-bus-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shenchuang006/spring-cloud
          search-paths: config-files
          username: 745372213@qq.com
          password: 19890302dear
          default-label: master
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

management:
  endpoint:
    bus-refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"